### ISSUE TITLE
[Study] 2020/04/26/일요일 스터디 쉼

### ISSUE THREAD

**Issue by algo2000** [leo-eun/testProject#31]
# Study 날짜 (년/월/일/요일)
> ### 년 월 일 요일

# Study 시간
> ### 시 부터
> ### 시 까지

# Study 장소
> ###

# Study 계획
> ###

**Comment by algo2000** [comment]
나 놀러감 @ruddms936  넌 시험보러가셈

**Comment by algo2000** [comment]
스발라마 답장안해 @ruddms936

**Comment by ruddms936** [comment]
> 스발라마 답장안해 @ruddms936 

바쁘다

**Comment by algo2000** [comment]
> > 스발라마 답장안해 @ruddms936 
> 
> 바쁘다
메일가는거를 확인하고 싶었단 말이다

**Comment by ruddms936** [comment]
.

**Comment by ruddms936** [comment]
> > > 스발라마 답장안해 @ruddms936 
> > 
> > 바쁘다
> 메일가는거를 확인하고 싶었단 말이다

아아 이러면 답장 되는건가

**Comment by algo2000** [comment]
> > > > 스발라마 답장안해 @ruddms936 
> > > 
> > > 바쁘다
> > 메일가는거를 확인하고 싶었단 말이다
> 
> 아아 이러면 답장 되는건가

도랐나
